### ISSUE TITLE
"Alignment-Based Replayer" generates Null Pointer

### ISSUE THREAD

**Issue by s-j-v-zelst** [pm4knime/pm4knime-development#23]
When I run the Alignment-Based Replayer, I obtain a NullPointerException

ERROR Alignment-Based Replayer 0:3        Execute failed: ("NullPointerException"): null

It seems that this is somehow related to settings not being correctly set?

**Comment by s-j-v-zelst** [comment]
java.lang.NullPointerException
	at org.deckfour.xes.model.impl.XLogImpl.getInfo(XLogImpl.java:253)
	at org.deckfour.xes.info.XLogInfoFactory.createLogInfo(XLogInfoFactory.java:73)
	at org.pm4knime.util.PetriNetUtil.constructMapping(PetriNetUtil.java:118)
	at org.pm4knime.node.conformance.replayer.DefaultPNReplayerNodeModel.executeWithoutLogger(DefaultPNReplayerNodeModel.java:181)
	at org.pm4knime.node.conformance.replayer.PNReplayerNodeModel.execute(PNReplayerNodeModel.java:33)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:567)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1192)
	at org.knime.core.node.Node.execute(Node.java:979)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:559)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:95)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:179)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:110)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:328)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:204)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)

**Comment by KFDing** [comment]
I am not sure about the reason behind it without the data and workflow. Please update to the new version. It should have fixed it now.
