### ISSUE TITLE
Alignment-Based Replayer: Using Lifecycle transition as a classifier provides a null pointer exception

### ISSUE THREAD

**Issue by s-j-v-zelst** [pm4knime/pm4knime-development#27]
2019-11-26 09:59:59,390 : ERROR : KNIME-Worker-14 :  : Node : Alignment-Based Replayer : 0:3 : Execute failed: ("NullPointerException"): null
java.lang.NullPointerException
	at org.processmining.plugins.astar.petrinet.impl.AbstractPDelegate.initTransitions(AbstractPDelegate.java:285)
	at org.processmining.plugins.astar.petrinet.impl.AbstractPDelegate.initialize(AbstractPDelegate.java:150)
	at org.processmining.plugins.astar.petrinet.impl.AbstractPDelegate.<init>(AbstractPDelegate.java:141)
	at org.processmining.plugins.astar.petrinet.impl.AbstractPILPDelegate.<init>(AbstractPILPDelegate.java:128)
	at org.processmining.plugins.astar.petrinet.impl.PILPDelegate.<init>(PILPDelegate.java:138)
	at org.processmining.plugins.astar.petrinet.impl.PILPDelegate.<init>(PILPDelegate.java:93)
	at org.processmining.plugins.astar.petrinet.PetrinetReplayerWithILP.getDelegate(PetrinetReplayerWithILP.java:75)
	at org.processmining.plugins.astar.petrinet.PetrinetReplayerWithILP.getDelegate(PetrinetReplayerWithILP.java:20)
	at org.processmining.plugins.astar.petrinet.AbstractPetrinetReplayer.replayLog(AbstractPetrinetReplayer.java:427)
	at org.pm4knime.node.conformance.replayer.DefaultPNReplayerNodeModel.executeWithoutLogger(DefaultPNReplayerNodeModel.java:186)
	at org.pm4knime.node.conformance.replayer.PNReplayerNodeModel.execute(PNReplayerNodeModel.java:33)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:567)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1192)
	at org.knime.core.node.Node.execute(Node.java:979)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:559)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:95)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:179)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:110)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:328)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:204)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)

**Comment by KFDing** [comment]
Have fixed the life transition problem now.
