### ISSUE TITLE
Performance Checker does not do a proper check on the input

### ISSUE THREAD

**Issue by s-j-v-zelst** [pm4knime/pm4knime-development#29]
WHen providing a replay result which was not generated with the manifest replayer (which can in some cases generate errors itself), we get the following error:

ERROR Performance Checker  0:7        Execute failed: Not supported attribute name

java.lang.IllegalArgumentException: Not supported attribute name
	at org.pm4knime.util.XLogUtil.getAttrClass(XLogUtil.java:291)
	at org.pm4knime.node.conformance.performance.PerfCheckerInfoAssistant.buildInfoParameter(PerfCheckerInfoAssistant.java:56)
	at org.pm4knime.node.conformance.performance.PerfCheckerInfoAssistant.<init>(PerfCheckerInfoAssistant.java:39)
	at org.pm4knime.node.conformance.performance.PerformanceCheckerNodeModel.execute(PerformanceCheckerNodeModel.java:155)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:567)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1192)
	at org.knime.core.node.Node.execute(Node.java:979)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:559)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:95)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:179)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:110)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:328)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:204)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)

**Comment by KFDing** [comment]
Hi @s-j-v-zelst ,

have fixed the bug and it could accept any inputs from the Replayer. But after changes, it might become a bit slow.
